export const APP_CONFIG = {
  appName: 'ETHX HRMS',
  companyName: 'ETHX Softcon Inc.',
  website: 'https://www.ethxsoftcon.com',
  tagline: 'Enterprise Human Capital & Workforce Intelligence',
  version: '2.0.0-PROD',
  defaultCurrency: 'USD',
};

export const DEMO_USERS = [
  {
    id: 'emp-005',
    email: 'niky.sharma@ethxsoftcon.com',
    name: 'Niky Sharma',
    role: 'HR Admin' as const,
    employeeId: 'ETHX-005',
    designation: 'Main HR',
    department: 'Human Resources',
    workLocation: 'Pune Global HQ',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-006',
    email: 'madhavi.singh@ethxsoftcon.com',
    name: 'Madhavi Singh',
    role: 'HR Executive' as const,
    employeeId: 'ETHX-006',
    designation: 'IT HR',
    department: 'Human Resources',
    workLocation: 'Pune Global HQ',
    password: 'hr123',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-004',
    email: 'siva.kumar@ethxsoftcon.com',
    name: 'Siva Kumar',
    role: 'Manager' as const,
    employeeId: 'ETHX-004',
    designation: 'IT Director / Manager',
    department: 'IT & Engineering',
    workLocation: 'Pune Global HQ',
    password: 'manager123',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-001',
    email: 'ram.chaturvedi@ethxsoftcon.com',
    name: 'Ram Chaturvedi',
    role: 'HR Admin' as const,
    employeeId: 'ETHX-001',
    designation: 'Company Director',
    department: 'Executive Board',
    workLocation: 'Pune Global HQ',
    password: 'director123',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-021',
    email: 'krishna.tiwari@ethxsoftcon.com',
    name: 'Krishna Tiwari',
    role: 'Employee' as const,
    employeeId: 'ETHX-021',
    designation: 'Unpaid Intern',
    department: 'IT & Engineering',
    workLocation: 'Pune Global HQ',
    password: 'intern123',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-007',
    email: 'shubham.patane@ethxsoftcon.com',
    name: 'Shubham Patane',
    role: 'Employee' as const,
    employeeId: 'ETHX-007',
    designation: 'Employee',
    department: 'IT & Engineering',
    workLocation: 'Pune Global HQ',
    password: 'employee123',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-017',
    email: 'utkarsh@ethxsoftcon.com',
    name: 'Utkarsh',
    role: 'Employee' as const,
    employeeId: 'ETHX-017',
    designation: 'Unpaid Intern',
    department: 'IT & Engineering',
    workLocation: 'Pune Global HQ',
    password: 'intern123',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-012',
    email: 'archit.sharma@ethxsoftcon.com',
    name: 'Archit Sharma',
    role: 'Employee' as const,
    employeeId: 'ETHX-012',
    designation: 'Employee (Contract-based)',
    department: 'Contract Operations',
    workLocation: 'Contract WFH',
    password: 'employee123',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
];
