import { 
  Employee, 
  Department, 
  Designation, 
  AttendanceRecord, 
  LeaveApplication, 
  SalarySlip, 
  JobOpening, 
  JobApplicant, 
  PerformanceGoal, 
  SkillMatrixItem, 
  AssetRecord, 
  HRNotification,
  InternshipLifecycleRecord,
  InternEvaluationRecord,
  ManagementDecisionRecord,
  EmploymentOfferRecord
} from '../types/hrms';

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'DEP-EXEC', name: 'Executive Board', headcount: 3, openPositions: 0, monthlyBudget: 0 },
  { id: 'DEP-IT', name: 'IT & Engineering', headcount: 14, openPositions: 2, monthlyBudget: 0 },
  { id: 'DEP-HR', name: 'Human Resources', headcount: 2, openPositions: 1, monthlyBudget: 0 },
  { id: 'DEP-OPS', name: 'Contract Operations', headcount: 2, openPositions: 0, monthlyBudget: 0 },
];

export const INITIAL_DESIGNATIONS: Designation[] = [
  { id: 'DES-01', name: 'Company Director', department: 'Executive Board' },
  { id: 'DES-02', name: 'IT Director / Manager', department: 'IT & Engineering' },
  { id: 'DES-03', name: 'Main HR', department: 'Human Resources' },
  { id: 'DES-04', name: 'IT HR', department: 'Human Resources' },
  { id: 'DES-05', name: 'Employee', department: 'IT & Engineering' },
  { id: 'DES-06', name: 'Employee (Contract-based)', department: 'Contract Operations' },
  { id: 'DES-07', name: 'Employee (Handles contract-related work)', department: 'Contract Operations' },
  { id: 'DES-08', name: 'Unpaid Intern', department: 'IT & Engineering' },
];

// Helper to construct unrated criteria snapshot without fabricated scores
export const createInitialCriteria = () => [
  { id: 'work_quality', label: 'Quality and accuracy of work', weight: 15, score: null, feedback: null },
  { id: 'task_completion', label: 'Task completion and reliability', weight: 15, score: null, feedback: null },
  { id: 'technical_skills', label: 'Technical or functional skills', weight: 15, score: null, feedback: null },
  { id: 'learning_progress', label: 'Learning progress', weight: 15, score: null, feedback: null },
  { id: 'communication', label: 'Communication', weight: 15, score: null, feedback: null },
  { id: 'teamwork', label: 'Teamwork', weight: 15, score: null, feedback: null },
  { id: 'conduct_attendance', label: 'Professional conduct and attendance', weight: 10, score: null, feedback: null },
];

// 8 Unpaid Interns confirmed shared details
const INTERN_NAMES = [
  { id: 'emp-014', employeeId: 'ETHX-014', firstName: 'Deepti', lastName: 'Tiwari', fullName: 'Deepti Tiwari' },
  { id: 'emp-015', employeeId: 'ETHX-015', firstName: 'Goraksh', lastName: 'Kaduskar', fullName: 'Goraksh Kaduskar' },
  { id: 'emp-016', employeeId: 'ETHX-016', firstName: 'Rushikesh', lastName: 'Kulkarni', fullName: 'Rushikesh Kulkarni' },
  { id: 'emp-017', employeeId: 'ETHX-017', firstName: 'Utkarsh', lastName: '', fullName: 'Utkarsh' }, // Preserved without surname
  { id: 'emp-018', employeeId: 'ETHX-018', firstName: 'Shakti', lastName: 'Thakur', fullName: 'Shakti Thakur' },
  { id: 'emp-019', employeeId: 'ETHX-019', firstName: 'Sayali', lastName: 'Mahant', fullName: 'Sayali Mahant' },
  { id: 'emp-020', employeeId: 'ETHX-020', firstName: 'Preeti', lastName: 'Bagal', fullName: 'Preeti Bagal' },
  { id: 'emp-021', employeeId: 'ETHX-021', firstName: 'Krishna', lastName: 'Tiwari', fullName: 'Krishna Tiwari' },
];

export const INITIAL_INTERNSHIP_LIFECYCLES: InternshipLifecycleRecord[] = INTERN_NAMES.map((intern) => ({
  internId: intern.id,
  internName: intern.fullName,
  startDate: '2026-07-01',
  scheduledEndDate: '2026-09-30',
  actualEndDate: null,
  dateState: 'Within internship period',
  administrativeOutcome: 'Completion pending',
  isExcludedFromPayroll: true,
  extensionHistory: [],
  earlyExitDetails: null,
  auditTrail: [
    {
      action: 'Internship Initialized',
      actor: 'System Roster Importer',
      timestamp: '2026-07-01T09:00:00Z',
      details: 'Unpaid internship registered from 1 July 2026 to 30 September 2026 (inclusive). Stipend: 0.',
    },
  ],
}));

export const INITIAL_INTERN_EVALUATIONS: InternEvaluationRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `EVAL-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  evaluationPeriod: 'Q3 2026 (01 Jul 2026 - 30 Sep 2026)',
  assignedReviewer: null,
  assignedApprover: null,
  reviewDeadline: '2026-09-28',
  status: 'Not Started',
  rubricVersion: 'v1.0 (7-Factor Quality & Reliability Rubric)',
  criteria: createInitialCriteria(),
  calculatedScore: null,
  strengths: null,
  improvementAreas: null,
  advisoryRecommendation: null,
  evidenceReferences: null,
  submissionDate: null,
  approvalDate: null,
  decisionRemarks: null,
  isDraftPrivate: true,
  revisionHistory: [],
}));

export const INITIAL_MANAGEMENT_DECISIONS: ManagementDecisionRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `DEC-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  evaluationId: `EVAL-2026-${String(idx + 1).padStart(3, '0')}`,
  decision: 'Pending decision',
  decidedBy: null,
  decisionDate: null,
  remarks: null,
  history: [],
}));

export const INITIAL_EMPLOYMENT_OFFERS: EmploymentOfferRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `OFFER-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  offerStatus: 'Draft',
  terms: {
    legalEmployer: 'ETHX Softcon Inc.',
    designation: 'Not provided',
    department: 'Not provided',
    reportingManager: 'Not provided',
    employmentArrangement: 'Not provided',
    proposedJoiningDate: '2026-10-01',
    actualJoiningDate: null,
    approvedSalary: null,
    salaryStructure: null,
    workLocation: 'Not provided',
    probationTerms: null,
  },
  preparedBy: null,
  approvedBy: null,
  issuedDate: null,
  responseDate: null,
  acceptanceStatus: 'Pending',
  conversionStatus: 'Unpaid Intern',
  effectiveConversionDate: null,
  activatedAt: null,
  history: [],
}));

// Master Confirmed 21 Personnel Dataset
export const INITIAL_EMPLOYEES: Employee[] = [
  // 1. Company Directors (3)
  {
    id: 'emp-001',
    employeeId: 'ETHX-001',
    firstName: 'Ram',
    lastName: 'Chaturvedi',
    fullName: 'Ram Chaturvedi',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-002',
    employeeId: 'ETHX-002',
    firstName: 'Rohan',
    lastName: '', // Preserved without inventing surname
    fullName: 'Rohan',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-003',
    employeeId: 'ETHX-003',
    firstName: 'Virender',
    lastName: 'Kumar',
    fullName: 'Virender Kumar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    responsibility: 'Handles ETHXSOFTCON US-based contract business',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 2. IT Leadership (1)
  {
    id: 'emp-004',
    employeeId: 'ETHX-004',
    firstName: 'Siva',
    lastName: 'Kumar',
    fullName: 'Siva Kumar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'IT & Engineering',
    designation: 'IT Director / Manager',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'IT Leadership',
    organisationalRole: 'IT Director / Manager',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Exact Designation Clarification', 'Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 3. HR Team (2)
  {
    id: 'emp-005',
    employeeId: 'ETHX-005',
    firstName: 'Niky',
    lastName: 'Sharma',
    fullName: 'Niky Sharma',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Human Resources',
    designation: 'Main HR',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'HR',
    organisationalRole: 'Main HR',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-006',
    employeeId: 'ETHX-006',
    firstName: 'Madhavi',
    lastName: 'Singh',
    fullName: 'Madhavi Singh',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Human Resources',
    designation: 'IT HR',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'HR',
    organisationalRole: 'IT HR',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 4. Employees (5)
  {
    id: 'emp-007',
    employeeId: 'ETHX-007',
    firstName: 'Shubham',
    lastName: 'Patane',
    fullName: 'Shubham Patane',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-008',
    employeeId: 'ETHX-008',
    firstName: 'Saurav',
    lastName: 'Sarkar',
    fullName: 'Saurav Sarkar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-009',
    employeeId: 'ETHX-009',
    firstName: 'Vishal',
    lastName: 'Walunj',
    fullName: 'Vishal Walunj',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-010',
    employeeId: 'ETHX-010',
    firstName: 'Shruti',
    lastName: 'Pawar',
    fullName: 'Shruti Pawar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-011',
    employeeId: 'ETHX-011',
    firstName: 'Ganesh',
    lastName: 'Kulkarni',
    fullName: 'Ganesh Kulkarni',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },

  // 5. Contract-Related Employees (2)
  {
    id: 'emp-012',
    employeeId: 'ETHX-012',
    firstName: 'Archit',
    lastName: 'Sharma',
    fullName: 'Archit Sharma',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Contract Operations',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Contract',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee (Contract-based)',
    employmentArrangement: 'Contract',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Contract Dates', 'Salary / Hourly Rate', 'Renewal Terms', 'Reporting Manager', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-013',
    employeeId: 'ETHX-013',
    firstName: 'Rajnesh',
    lastName: '', // Preserved without inventing surname
    fullName: 'Rajnesh',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Contract Operations',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee (Handles contract-related work)',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Salary / Compensation', 'Designation Specifics', 'Reporting Manager', 'Official Email', 'Phone', 'Work Location'],
  },

  // 6. Unpaid Interns (8)
  ...INTERN_NAMES.map((intern) => ({
    id: intern.id,
    employeeId: intern.employeeId,
    firstName: intern.firstName,
    lastName: intern.lastName,
    fullName: intern.fullName,
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Unpaid Intern',
    joiningDate: '2026-07-01',
    status: 'Active' as const,
    employmentType: 'Intern' as const,
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: 0,
    salaryCurrency: 'USD',
    engagementCategory: 'Intern' as const,
    organisationalRole: 'Unpaid Intern',
    employmentArrangement: 'Internship' as const,
    compensationStatus: 'Unpaid' as const,
    stipend: 0,
    profileCompleteness: 'Incomplete' as const,
    missingFields: ['Department', 'Supervisor / Reporting Manager', 'Official Email', 'Phone', 'Work Location', 'Working Hours'],
    internshipDetails: {
      internId: intern.id,
      internName: intern.fullName,
      startDate: '2026-07-01',
      scheduledEndDate: '2026-09-30',
      actualEndDate: null,
      dateState: 'Within internship period' as const,
      administrativeOutcome: 'Completion pending' as const,
      isExcludedFromPayroll: true,
      extensionHistory: [],
      earlyExitDetails: null,
      auditTrail: [
        {
          action: 'Internship Registered',
          actor: 'System Initializer',
          timestamp: '2026-07-01T09:00:00Z',
          details: 'Unpaid internship registered for 1 July - 30 Sept 2026 (inclusive). Stipend: 0. Excluded from payroll.',
        },
      ],
    },
    conversionDetails: {
      conversionStatus: 'Unpaid Intern' as const,
    },
  })),
];

// Comprehensive Attendance Ledger across all 21 Personnel
const TRACKING_DATES = ['2026-09-28', '2026-09-25', '2026-09-24', '2026-09-23'];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = TRACKING_DATES.flatMap((dateStr) => {
  const isThuOrFri = dateStr === '2026-09-24' || dateStr === '2026-09-25';

  return INITIAL_EMPLOYEES.map((emp, idx) => {
    const isIntern = emp.engagementCategory === 'Intern';
    const isContractWfh = emp.employmentArrangement === 'Contract' || emp.workLocation?.includes('WFH') || emp.fullName === 'Archit Sharma';
    const isUsContract = emp.fullName === 'Virender Kumar';

    let scheduledMode: 'WFO' | 'WFH' = 'WFO';
    let actualMode: 'WFO' | 'WFH' = 'WFO';
    let location = 'Pune HQ (Main Campus)';

    if (isIntern) {
      scheduledMode = isThuOrFri ? 'WFH' : 'WFO';
      actualMode = scheduledMode;
      location = isThuOrFri ? 'Remote WFH' : 'Pune HQ (Main Campus)';
    } else if (isContractWfh) {
      scheduledMode = 'WFH';
      actualMode = 'WFH';
      location = 'Remote Contract WFH (Pan-India)';
    } else if (isUsContract) {
      scheduledMode = 'WFH';
      actualMode = 'WFH';
      location = 'Remote Executive (US Operations)';
    }

    const checkInHour = 8 + (idx % 2); // 8 AM or 9 AM
    const checkInMin = String(5 + ((idx * 7) % 50)).padStart(2, '0');
    const checkOutHour = 5 + ((idx % 3)); // 5 PM, 6 PM, 7 PM
    const checkOutMin = String(10 + ((idx * 11) % 45)).padStart(2, '0');
    const hours = Number((8.0 + ((idx % 5) * 0.25)).toFixed(1));

    return {
      id: `ATT-${dateStr.replace(/-/g, '')}-${emp.employeeId}`,
      employeeId: emp.employeeId,
      employeeName: emp.fullName,
      department: emp.department !== 'Not provided' ? emp.department : (isIntern ? 'Engineering & Cloud' : 'Operations'),
      date: dateStr,
      scheduledWorkMode: scheduledMode,
      actualWorkMode: actualMode,
      checkIn: `0${checkInHour}:${checkInMin} AM`,
      checkOut: `0${checkOutHour}:${checkOutMin} PM`,
      status: 'Present' as const,
      workHours: hours,
      location,
      dataCoverage: 'Recorded' as const,
      correctionHistory: [],
    };
  });
});

export const INITIAL_LEAVE_APPLICATIONS: LeaveApplication[] = [];

export const INITIAL_SALARY_SLIPS: SalarySlip[] = [];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  { id: 'JOB-201', title: 'Permanent Software Engineer (Conversion)', department: 'IT & Engineering', location: 'Pune HQ', employmentType: 'Full-time', openPositions: 4, applicantsCount: 8, status: 'Published', publishDate: '2026-09-15', experienceLevel: 'Graduate / Intern', salaryRange: 'Competitive' },
];

export const INITIAL_JOB_APPLICANTS: JobApplicant[] = [];

export const INITIAL_GOALS: PerformanceGoal[] = [
  { id: 'G-101', employeeId: 'ETHX-021', title: 'Complete Q3 Internship Capstone Deliverable', description: 'Deliver full-fidelity module specifications and evaluation evidence before 30 Sep 2026.', category: 'Operational', progress: 90, dueDate: '2026-09-30', weightage: 50, status: 'In Progress' },
];

export const INITIAL_SKILLS: SkillMatrixItem[] = [
  {
    id: 'SK-01',
    skillName: 'React 18, TypeScript & Next.js UI/UX',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 12,
    targetDemand: 14,
    gapPriority: 'Moderate',
    learningTrack: 'Frontend Engineering Specialization',
    description: 'Concurrent rendering, memoization, atomic design systems, and TypeScript 5.7 strict typing.',
    certifiedEmployees: ['Shubham Patane', 'Saurav Sarkar', 'Shruti Pawar', 'Krishna Tiwari', 'Rushikesh Kulkarni'],
  },
  {
    id: 'SK-02',
    skillName: 'Python, Frappe Framework & ERPNext',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Advanced',
    employeeCount: 8,
    targetDemand: 10,
    gapPriority: 'Moderate',
    learningTrack: 'Frappe Cloud Architecture',
    description: 'DocType modeling, server scripts, RESTful API hooks, and Frappe bench administration on port 8280.',
    certifiedEmployees: ['Siva Kumar', 'Shubham Patane', 'Deepti Tiwari', 'Goraksh Kaduskar'],
  },
  {
    id: 'SK-03',
    skillName: 'Docker, Linux Server & Nginx Reverse Proxy',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Intermediate',
    employeeCount: 7,
    targetDemand: 8,
    gapPriority: 'Moderate',
    learningTrack: 'Cloud DevOps & Containerization',
    description: 'Multi-stage Docker builds, Alpine Linux, Nginx SPA routing fallback, and container networking.',
    certifiedEmployees: ['Siva Kumar', 'Virender Kumar', 'Krishna Tiwari', 'Utkarsh'],
  },
  {
    id: 'SK-04',
    skillName: 'MariaDB / MySQL Relational Schema & ACID',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 9,
    targetDemand: 10,
    gapPriority: 'Optimal',
    learningTrack: 'Database Engineering',
    description: 'Relational data modeling, indexing, foreign keys, transaction isolation, and query optimization.',
    certifiedEmployees: ['Siva Kumar', 'Saurav Sarkar', 'Vishal Walunj', 'Preeti Bagal'],
  },
  {
    id: 'SK-05',
    skillName: 'RESTful API Contracts & Client Data Sync',
    category: 'Engineering',
    proficiencyLevel: 'Expert',
    employeeCount: 11,
    targetDemand: 12,
    gapPriority: 'Optimal',
    learningTrack: 'Distributed API Systems',
    description: 'JSON schemas, bearer token authentication, idempotent state sync, and optimistic UI updates.',
    certifiedEmployees: ['Siva Kumar', 'Shruti Pawar', 'Ganesh Kulkarni', 'Sayali Mahant'],
  },
  {
    id: 'SK-06',
    skillName: 'Vitest, Unit Testing & QA Automation',
    category: 'Engineering',
    proficiencyLevel: 'Intermediate',
    employeeCount: 6,
    targetDemand: 8,
    gapPriority: 'Moderate',
    learningTrack: 'Software Quality Assurance',
    description: 'Component unit tests, API integration tests, assertion coverage, and regression prevention.',
    certifiedEmployees: ['Shubham Patane', 'Shruti Pawar', 'Shakti Thakur'],
  },
  {
    id: 'SK-07',
    skillName: 'Statutory Payroll, PF & Indian Labor Compliance',
    category: 'HR & Operations',
    proficiencyLevel: 'Expert',
    employeeCount: 2,
    targetDemand: 2,
    gapPriority: 'Optimal',
    learningTrack: 'HR Legal & Statutory Governance',
    description: 'Salary slip generation, tax deductions, PF calculation, and labor compliance regulation.',
    certifiedEmployees: ['Niky Sharma', 'Madhavi Singh'],
  },
  {
    id: 'SK-08',
    skillName: 'Performance Evaluation Rubrics & OKRs',
    category: 'HR & Operations',
    proficiencyLevel: 'Advanced',
    employeeCount: 3,
    targetDemand: 3,
    gapPriority: 'Optimal',
    learningTrack: 'Strategic HR Performance',
    description: '7-Factor evaluation rubrics, conversion recommendation pipelines, and OKR milestone tracking.',
    certifiedEmployees: ['Niky Sharma', 'Madhavi Singh', 'Ram Chaturvedi'],
  },
  {
    id: 'SK-09',
    skillName: 'Redis In-Memory Caching & Task Queues',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Intermediate',
    employeeCount: 5,
    targetDemand: 6,
    gapPriority: 'Moderate',
    learningTrack: 'High-Performance Caching',
    description: 'Redis 6.2 key-value caching, session token storage, and asynchronous background worker queues.',
    certifiedEmployees: ['Siva Kumar', 'Krishna Tiwari', 'Goraksh Kaduskar'],
  },
  {
    id: 'SK-10',
    skillName: 'Git Version Control & CI/CD Pipelines',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 18,
    targetDemand: 18,
    gapPriority: 'Optimal',
    learningTrack: 'DevOps & Collaboration',
    description: 'Git branching, semantic commit tagging, pull request reviews, and GitHub Actions automation.',
    certifiedEmployees: ['All 14 Engineers & Interns', 'Siva Kumar', 'Archit Sharma'],
  },
];

export const INITIAL_ASSETS: AssetRecord[] = [
  // 1. Unpaid Intern Cohort (8 Asus Vivobooks)
  {
    id: 'AST-ASUS-014',
    assetCode: 'ETHX-VIVO-014',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-014',
    assignedEmployeeName: 'Deepti Tiwari',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77014',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-015',
    assetCode: 'ETHX-VIVO-015',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-015',
    assignedEmployeeName: 'Goraksh Kaduskar',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77015',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-016',
    assetCode: 'ETHX-VIVO-016',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-016',
    assignedEmployeeName: 'Rushikesh Kulkarni',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77016',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-017',
    assetCode: 'ETHX-VIVO-017',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-017',
    assignedEmployeeName: 'Utkarsh',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77017',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-018',
    assetCode: 'ETHX-VIVO-018',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-018',
    assignedEmployeeName: 'Shakti Thakur',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77018',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-019',
    assetCode: 'ETHX-VIVO-019',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-019',
    assignedEmployeeName: 'Sayali Mahant',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77019',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-020',
    assetCode: 'ETHX-VIVO-020',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-020',
    assignedEmployeeName: 'Preeti Bagal',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77020',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-021',
    assetCode: 'ETHX-VIVO-021',
    assetName: 'Asus Vivobook 15 Pro OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook Pro 15 OLED M6500',
    specifications: 'AMD Ryzen 7 / Intel Core i5 • 16GB DDR5 • 512GB NVMe SSD • NVIDIA RTX Graphics',
    assignedTo: 'ETHX-021',
    assignedEmployeeName: 'Krishna Tiwari',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VBP-77021',
    condition: 'Brand New',
  },

  // 2. Full-time Employees & HR (HP Laptops)
  {
    id: 'AST-HP-004',
    assetCode: 'ETHX-HP-004',
    assetName: 'HP ZBook Firefly 14 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ZBook Firefly 14 G10 Mobile Workstation',
    specifications: 'Intel Core i7 13th Gen • 32GB DDR5 • 1TB NVMe Gen4 SSD • NVIDIA RTX A500',
    assignedTo: 'ETHX-004',
    assignedEmployeeName: 'Siva Kumar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-05-15',
    status: 'In Use',
    purchaseDate: '2023-05-01',
    warrantyExpiry: '2026-05-01',
    serialNumber: '5CG3190HP4',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-005',
    assetCode: 'ETHX-HP-005',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR5 • 512GB NVMe SSD • Sure View Privacy',
    assignedTo: 'ETHX-005',
    assignedEmployeeName: 'Niky Sharma',
    assignedDepartment: 'Human Resources',
    allocatedDate: '2023-06-01',
    status: 'In Use',
    purchaseDate: '2023-05-20',
    warrantyExpiry: '2026-05-20',
    serialNumber: '5CG3210HP5',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-006',
    assetCode: 'ETHX-HP-006',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR5 • 512GB NVMe SSD • HP Wolf Security',
    assignedTo: 'ETHX-006',
    assignedEmployeeName: 'Madhavi Singh',
    assignedDepartment: 'Human Resources',
    allocatedDate: '2023-11-10',
    status: 'In Use',
    purchaseDate: '2023-11-01',
    warrantyExpiry: '2026-11-01',
    serialNumber: '5CG3450HP6',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-007',
    assetCode: 'ETHX-HP-007',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-007',
    assignedEmployeeName: 'Shubham Patane',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-11-20',
    status: 'In Use',
    purchaseDate: '2023-11-15',
    warrantyExpiry: '2026-11-15',
    serialNumber: '5CG3520HP7',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-008',
    assetCode: 'ETHX-HP-008',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-008',
    assignedEmployeeName: 'Saurav Sarkar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-12-05',
    status: 'In Use',
    purchaseDate: '2023-11-28',
    warrantyExpiry: '2026-11-28',
    serialNumber: '5CG3590HP8',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-009',
    assetCode: 'ETHX-HP-009',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-009',
    assignedEmployeeName: 'Vishal Walunj',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2024-02-01',
    status: 'In Use',
    purchaseDate: '2024-01-20',
    warrantyExpiry: '2027-01-20',
    serialNumber: '5CG4080HP9',
    condition: 'Good',
  },
  {
    id: 'AST-HP-010',
    assetCode: 'ETHX-HP-010',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR5 • 512GB NVMe SSD • HP Wolf Security',
    assignedTo: 'ETHX-010',
    assignedEmployeeName: 'Shruti Pawar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-08-15',
    status: 'In Use',
    purchaseDate: '2023-08-01',
    warrantyExpiry: '2026-08-01',
    serialNumber: '5CG3380HP10',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-011',
    assetCode: 'ETHX-HP-011',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-011',
    assignedEmployeeName: 'Ganesh Kulkarni',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2024-01-10',
    status: 'In Use',
    purchaseDate: '2023-12-20',
    warrantyExpiry: '2026-12-20',
    serialNumber: '5CG4010HP11',
    condition: 'Good',
  },
  {
    id: 'AST-HP-012',
    assetCode: 'ETHX-HP-012',
    assetName: 'HP EliteBook 650 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 650 G9 Secure Remote',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • VPN Hardware Token Enrolled',
    assignedTo: 'ETHX-012',
    assignedEmployeeName: 'Archit Sharma',
    assignedDepartment: 'Contract Operations (Pan-India)',
    allocatedDate: '2023-11-15',
    status: 'In Use',
    purchaseDate: '2023-11-01',
    warrantyExpiry: '2026-11-01',
    serialNumber: '5CG3480HP12',
    condition: 'Good',
  },
  {
    id: 'AST-HP-013',
    assetCode: 'ETHX-HP-013',
    assetName: 'HP EliteBook 650 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 650 G9 Secure Remote',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • VPN Hardware Token Enrolled',
    assignedTo: 'ETHX-013',
    assignedEmployeeName: 'Rajnesh',
    assignedDepartment: 'Contract Operations (Pan-India)',
    allocatedDate: '2024-02-12',
    status: 'In Use',
    purchaseDate: '2024-02-01',
    warrantyExpiry: '2027-02-01',
    serialNumber: '5CG4120HP13',
    condition: 'Good',
  },

  // 3. Executive Board Directors (HP Enterprise & Spectre)
  {
    id: 'AST-HP-001',
    assetCode: 'ETHX-HP-001',
    assetName: 'HP Spectre x360 16"',
    category: 'Laptop',
    brand: 'HP',
    model: 'Spectre x360 2-in-1 OLED',
    specifications: 'Intel Core i7 13th Gen • 32GB LPDDR5 • 1TB NVMe Gen4 SSD • 4K OLED Touch',
    assignedTo: 'ETHX-001',
    assignedEmployeeName: 'Ram Chaturvedi',
    assignedDepartment: 'Executive Board',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2420HP1',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-002',
    assetCode: 'ETHX-HP-002',
    assetName: 'HP Elite Dragonfly G4',
    category: 'Laptop',
    brand: 'HP',
    model: 'Elite Dragonfly G4 Ultralight',
    specifications: 'Intel Core i7 13th Gen • 32GB LPDDR5 • 1TB SSD • 5G LTE eSIM Active',
    assignedTo: 'ETHX-002',
    assignedEmployeeName: 'Rohan',
    assignedDepartment: 'Executive Board',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2440HP2',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-003',
    assetCode: 'ETHX-HP-003',
    assetName: 'HP ZBook Studio G9 Workstation',
    category: 'Laptop',
    brand: 'HP',
    model: 'ZBook Studio G9 Workstation',
    specifications: 'Intel Core i9 12th Gen • 32GB DDR5 • 1TB SSD • NVIDIA RTX 3070 Ti',
    assignedTo: 'ETHX-003',
    assignedEmployeeName: 'Virender Kumar',
    assignedDepartment: 'Executive Board (US Operations)',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2490HP3',
    condition: 'Excellent',
  },

  // 4. IT Inventory Reserves (Available Spares & Service)
  {
    id: 'AST-ASUS-RES-01',
    assetCode: 'ETHX-VIVO-RES1',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • Unboxed / Provisioned',
    status: 'Available',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77091',
    condition: 'Brand New',
  },
  {
    id: 'AST-HP-RES-01',
    assetCode: 'ETHX-HP-RES1',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • IT Pune Spare',
    status: 'Available',
    purchaseDate: '2024-03-01',
    warrantyExpiry: '2027-03-01',
    serialNumber: '5CG4110HP-RES',
    condition: 'Brand New',
  },
  {
    id: 'AST-HP-MNT-01',
    assetCode: 'ETHX-HP-MNT1',
    assetName: 'HP EliteBook 840 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G9 Enterprise',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • Battery Diagnostic',
    status: 'Under Maintenance',
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    serialNumber: '5CG3010HP-MNT',
    condition: 'Needs Service',
  },
];

export const INITIAL_NOTIFICATIONS: HRNotification[] = [
  { id: 'NOTIF-01', title: 'Internship Evaluation Review Period Open', message: 'Evaluation period active for 8 unpaid interns concluding on 30 Sep 2026.', timestamp: '1 hour ago', type: 'performance', read: false, actionUrl: '/internships' },
];
