import { 
  Employee, 
  Department, 
  Designation, 
  AttendanceRecord, 
  LeaveApplication, 
  SalarySlip, 
  JobOpening, 
  JobApplicant, 
  PerformanceGoal, 
  SkillMatrixItem, 
  AssetRecord, 
  HRNotification,
  InternshipLifecycleRecord,
  InternEvaluationRecord,
  ManagementDecisionRecord,
  EmploymentOfferRecord
} from '../types/hrms';

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'DEP-EXEC', name: 'Executive Board', headcount: 3, openPositions: 0, monthlyBudget: 0 },
  { id: 'DEP-IT', name: 'IT & Engineering', headcount: 14, openPositions: 2, monthlyBudget: 0 },
  { id: 'DEP-HR', name: 'Human Resources', headcount: 2, openPositions: 1, monthlyBudget: 0 },
  { id: 'DEP-OPS', name: 'Contract Operations', headcount: 2, openPositions: 0, monthlyBudget: 0 },
];

export const INITIAL_DESIGNATIONS: Designation[] = [
  { id: 'DES-01', name: 'Company Director', department: 'Executive Board' },
  { id: 'DES-02', name: 'IT Director / Manager', department: 'IT & Engineering' },
  { id: 'DES-03', name: 'Main HR', department: 'Human Resources' },
  { id: 'DES-04', name: 'IT HR', department: 'Human Resources' },
  { id: 'DES-05', name: 'Employee', department: 'IT & Engineering' },
  { id: 'DES-06', name: 'Employee (Contract-based)', department: 'Contract Operations' },
  { id: 'DES-07', name: 'Employee (Handles contract-related work)', department: 'Contract Operations' },
  { id: 'DES-08', name: 'Unpaid Intern', department: 'IT & Engineering' },
];

// Helper to construct unrated criteria snapshot without fabricated scores
export const createInitialCriteria = () => [
  { id: 'work_quality', label: 'Quality and accuracy of work', weight: 15, score: null, feedback: null },
  { id: 'task_completion', label: 'Task completion and reliability', weight: 15, score: null, feedback: null },
  { id: 'technical_skills', label: 'Technical or functional skills', weight: 15, score: null, feedback: null },
  { id: 'learning_progress', label: 'Learning progress', weight: 15, score: null, feedback: null },
  { id: 'communication', label: 'Communication', weight: 15, score: null, feedback: null },
  { id: 'teamwork', label: 'Teamwork', weight: 15, score: null, feedback: null },
  { id: 'conduct_attendance', label: 'Professional conduct and attendance', weight: 10, score: null, feedback: null },
];

// 8 Unpaid Interns confirmed shared details
const INTERN_NAMES = [
  { id: 'emp-014', employeeId: 'ETHX-014', firstName: 'Deepti', lastName: 'Tiwari', fullName: 'Deepti Tiwari' },
  { id: 'emp-015', employeeId: 'ETHX-015', firstName: 'Goraksh', lastName: 'Kaduskar', fullName: 'Goraksh Kaduskar' },
  { id: 'emp-016', employeeId: 'ETHX-016', firstName: 'Rushikesh', lastName: 'Kulkarni', fullName: 'Rushikesh Kulkarni' },
  { id: 'emp-017', employeeId: 'ETHX-017', firstName: 'Utkarsh', lastName: '', fullName: 'Utkarsh' }, // Preserved without surname
  { id: 'emp-018', employeeId: 'ETHX-018', firstName: 'Shakti', lastName: 'Thakur', fullName: 'Shakti Thakur' },
  { id: 'emp-019', employeeId: 'ETHX-019', firstName: 'Sayali', lastName: 'Mahant', fullName: 'Sayali Mahant' },
  { id: 'emp-020', employeeId: 'ETHX-020', firstName: 'Preeti', lastName: 'Bagal', fullName: 'Preeti Bagal' },
  { id: 'emp-021', employeeId: 'ETHX-021', firstName: 'Krishna', lastName: 'Tiwari', fullName: 'Krishna Tiwari' },
];

export const INITIAL_INTERNSHIP_LIFECYCLES: InternshipLifecycleRecord[] = INTERN_NAMES.map((intern) => ({
  internId: intern.id,
  internName: intern.fullName,
  startDate: '2026-07-01',
  scheduledEndDate: '2026-09-30',
  actualEndDate: null,
  dateState: 'Within internship period',
  administrativeOutcome: 'Completion pending',
  isExcludedFromPayroll: true,
  extensionHistory: [],
  earlyExitDetails: null,
  auditTrail: [
    {
      action: 'Internship Initialized',
      actor: 'System Roster Importer',
      timestamp: '2026-07-01T09:00:00Z',
      details: 'Unpaid internship registered from 1 July 2026 to 30 September 2026 (inclusive). Stipend: 0.',
    },
  ],
}));

export const INITIAL_INTERN_EVALUATIONS: InternEvaluationRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `EVAL-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  evaluationPeriod: 'Q3 2026 (01 Jul 2026 - 30 Sep 2026)',
  assignedReviewer: null,
  assignedApprover: null,
  reviewDeadline: '2026-09-28',
  status: 'Not Started',
  rubricVersion: 'v1.0 (7-Factor Quality & Reliability Rubric)',
  criteria: createInitialCriteria(),
  calculatedScore: null,
  strengths: null,
  improvementAreas: null,
  advisoryRecommendation: null,
  evidenceReferences: null,
  submissionDate: null,
  approvalDate: null,
  decisionRemarks: null,
  isDraftPrivate: true,
  revisionHistory: [],
}));

export const INITIAL_MANAGEMENT_DECISIONS: ManagementDecisionRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `DEC-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  evaluationId: `EVAL-2026-${String(idx + 1).padStart(3, '0')}`,
  decision: 'Pending decision',
  decidedBy: null,
  decisionDate: null,
  remarks: null,
  history: [],
}));

export const INITIAL_EMPLOYMENT_OFFERS: EmploymentOfferRecord[] = INTERN_NAMES.map((intern, idx) => ({
  id: `OFFER-2026-${String(idx + 1).padStart(3, '0')}`,
  internId: intern.id,
  internName: intern.fullName,
  offerStatus: 'Draft',
  terms: {
    legalEmployer: 'ETHX Softcon Inc.',
    designation: 'Not provided',
    department: 'Not provided',
    reportingManager: 'Not provided',
    employmentArrangement: 'Not provided',
    proposedJoiningDate: '2026-10-01',
    actualJoiningDate: null,
    approvedSalary: null,
    salaryStructure: null,
    workLocation: 'Not provided',
    probationTerms: null,
  },
  preparedBy: null,
  approvedBy: null,
  issuedDate: null,
  responseDate: null,
  acceptanceStatus: 'Pending',
  conversionStatus: 'Unpaid Intern',
  effectiveConversionDate: null,
  activatedAt: null,
  history: [],
}));

// Master Confirmed 21 Personnel Dataset
export const INITIAL_EMPLOYEES: Employee[] = [
  // 1. Company Directors (3)
  {
    id: 'emp-001',
    employeeId: 'ETHX-001',
    firstName: 'Ram',
    lastName: 'Chaturvedi',
    fullName: 'Ram Chaturvedi',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-002',
    employeeId: 'ETHX-002',
    firstName: 'Rohan',
    lastName: '', // Preserved without inventing surname
    fullName: 'Rohan',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-003',
    employeeId: 'ETHX-003',
    firstName: 'Virender',
    lastName: 'Kumar',
    fullName: 'Virender Kumar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Executive Board',
    designation: 'Company Director',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Company Director',
    organisationalRole: 'Company Director',
    responsibility: 'Handles ETHXSOFTCON US-based contract business',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 2. IT Leadership (1)
  {
    id: 'emp-004',
    employeeId: 'ETHX-004',
    firstName: 'Siva',
    lastName: 'Kumar',
    fullName: 'Siva Kumar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'IT & Engineering',
    designation: 'IT Director / Manager',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'IT Leadership',
    organisationalRole: 'IT Director / Manager',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Exact Designation Clarification', 'Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 3. HR Team (2)
  {
    id: 'emp-005',
    employeeId: 'ETHX-005',
    firstName: 'Niky',
    lastName: 'Sharma',
    fullName: 'Niky Sharma',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Human Resources',
    designation: 'Main HR',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'HR',
    organisationalRole: 'Main HR',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-006',
    employeeId: 'ETHX-006',
    firstName: 'Madhavi',
    lastName: 'Singh',
    fullName: 'Madhavi Singh',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Human Resources',
    designation: 'IT HR',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'HR',
    organisationalRole: 'IT HR',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Terms', 'Compensation / Salary', 'Official Email', 'Phone', 'Work Location'],
  },

  // 4. Employees (5)
  {
    id: 'emp-007',
    employeeId: 'ETHX-007',
    firstName: 'Shubham',
    lastName: 'Patane',
    fullName: 'Shubham Patane',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-008',
    employeeId: 'ETHX-008',
    firstName: 'Saurav',
    lastName: 'Sarkar',
    fullName: 'Saurav Sarkar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-009',
    employeeId: 'ETHX-009',
    firstName: 'Vishal',
    lastName: 'Walunj',
    fullName: 'Vishal Walunj',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-010',
    employeeId: 'ETHX-010',
    firstName: 'Shruti',
    lastName: 'Pawar',
    fullName: 'Shruti Pawar',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },
  {
    id: 'emp-011',
    employeeId: 'ETHX-011',
    firstName: 'Ganesh',
    lastName: 'Kulkarni',
    fullName: 'Ganesh Kulkarni',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Designation', 'Department', 'Joining Date', 'Salary', 'Probation Terms', 'Reporting Manager'],
  },

  // 5. Contract-Related Employees (2)
  {
    id: 'emp-012',
    employeeId: 'ETHX-012',
    firstName: 'Archit',
    lastName: 'Sharma',
    fullName: 'Archit Sharma',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Contract Operations',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Contract',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee (Contract-based)',
    employmentArrangement: 'Contract',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Contract Dates', 'Salary / Hourly Rate', 'Renewal Terms', 'Reporting Manager', 'Official Email', 'Phone', 'Work Location'],
  },
  {
    id: 'emp-013',
    employeeId: 'ETHX-013',
    firstName: 'Rajnesh',
    lastName: '', // Preserved without inventing surname
    fullName: 'Rajnesh',
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Contract Operations',
    designation: 'Employee',
    joiningDate: 'Not provided',
    status: 'Active',
    employmentType: 'Full-time',
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: null,
    salaryCurrency: 'USD',
    engagementCategory: 'Employee',
    organisationalRole: 'Employee (Handles contract-related work)',
    employmentArrangement: 'Not provided',
    compensationStatus: 'Not provided',
    stipend: null,
    profileCompleteness: 'Incomplete',
    missingFields: ['Employment Arrangement', 'Salary / Compensation', 'Designation Specifics', 'Reporting Manager', 'Official Email', 'Phone', 'Work Location'],
  },

  // 6. Unpaid Interns (8)
  ...INTERN_NAMES.map((intern) => ({
    id: intern.id,
    employeeId: intern.employeeId,
    firstName: intern.firstName,
    lastName: intern.lastName,
    fullName: intern.fullName,
    email: 'Not provided',
    phone: 'Not provided',
    department: 'Not provided',
    designation: 'Unpaid Intern',
    joiningDate: '2026-07-01',
    status: 'Active' as const,
    employmentType: 'Intern' as const,
    workLocation: 'Not provided',
    shift: 'Not provided',
    baseSalary: 0,
    salaryCurrency: 'USD',
    engagementCategory: 'Intern' as const,
    organisationalRole: 'Unpaid Intern',
    employmentArrangement: 'Internship' as const,
    compensationStatus: 'Unpaid' as const,
    stipend: 0,
    profileCompleteness: 'Incomplete' as const,
    missingFields: ['Department', 'Supervisor / Reporting Manager', 'Official Email', 'Phone', 'Work Location', 'Working Hours'],
    internshipDetails: {
      internId: intern.id,
      internName: intern.fullName,
      startDate: '2026-07-01',
      scheduledEndDate: '2026-09-30',
      actualEndDate: null,
      dateState: 'Within internship period' as const,
      administrativeOutcome: 'Completion pending' as const,
      isExcludedFromPayroll: true,
      extensionHistory: [],
      earlyExitDetails: null,
      auditTrail: [
        {
          action: 'Internship Registered',
          actor: 'System Initializer',
          timestamp: '2026-07-01T09:00:00Z',
          details: 'Unpaid internship registered for 1 July - 30 Sept 2026 (inclusive). Stipend: 0. Excluded from payroll.',
        },
      ],
    },
    conversionDetails: {
      conversionStatus: 'Unpaid Intern' as const,
    },
  })),
];

// Comprehensive Attendance Ledger across all 21 Personnel
const TRACKING_DATES = ['2026-09-28', '2026-09-25', '2026-09-24', '2026-09-23'];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = TRACKING_DATES.flatMap((dateStr) => {
  const isThuOrFri = dateStr === '2026-09-24' || dateStr === '2026-09-25';

  return INITIAL_EMPLOYEES.map((emp, idx) => {
    const isIntern = emp.engagementCategory === 'Intern';
    const isContractWfh = emp.employmentArrangement === 'Contract' || emp.workLocation?.includes('WFH') || emp.fullName === 'Archit Sharma';
    const isUsContract = emp.fullName === 'Virender Kumar';

    let scheduledMode: 'WFO' | 'WFH' = 'WFO';
    let actualMode: 'WFO' | 'WFH' = 'WFO';
    let location = 'Pune HQ (Main Campus)';

    if (isIntern) {
      scheduledMode = isThuOrFri ? 'WFH' : 'WFO';
      actualMode = scheduledMode;
      location = isThuOrFri ? 'Remote WFH' : 'Pune HQ (Main Campus)';
    } else if (isContractWfh) {
      scheduledMode = 'WFH';
      actualMode = 'WFH';
      location = 'Remote Contract WFH (Pan-India)';
    } else if (isUsContract) {
      scheduledMode = 'WFH';
      actualMode = 'WFH';
      location = 'Remote Executive (US Operations)';
    }

    const checkInHour = 8 + (idx % 2); // 8 AM or 9 AM
    const checkInMin = String(5 + ((idx * 7) % 50)).padStart(2, '0');
    const checkOutHour = 5 + ((idx % 3)); // 5 PM, 6 PM, 7 PM
    const checkOutMin = String(10 + ((idx * 11) % 45)).padStart(2, '0');
    const hours = Number((8.0 + ((idx % 5) * 0.25)).toFixed(1));

    return {
      id: `ATT-${dateStr.replace(/-/g, '')}-${emp.employeeId}`,
      employeeId: emp.employeeId,
      employeeName: emp.fullName,
      department: emp.department !== 'Not provided' ? emp.department : (isIntern ? 'Engineering & Cloud' : 'Operations'),
      date: dateStr,
      scheduledWorkMode: scheduledMode,
      actualWorkMode: actualMode,
      checkIn: `0${checkInHour}:${checkInMin} AM`,
      checkOut: `0${checkOutHour}:${checkOutMin} PM`,
      status: 'Present' as const,
      workHours: hours,
      location,
      dataCoverage: 'Recorded' as const,
      correctionHistory: [],
    };
  });
});

export const INITIAL_LEAVE_APPLICATIONS: LeaveApplication[] = [];

export const INITIAL_SALARY_SLIPS: SalarySlip[] = [];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  { id: 'JOB-201', title: 'Full-Stack Software Engineer (React / TypeScript / Node)', department: 'IT & Engineering', location: 'Pune Global HQ', employmentType: 'Full-time', openPositions: 3, applicantsCount: 5, status: 'Published', publishDate: '2026-09-15', experienceLevel: 'Mid-Senior (2-5 yrs)', salaryRange: '₹14 - 22 LPA' },
  { id: 'JOB-202', title: 'Cloud DevOps & Site Reliability Engineer', department: 'Cloud & Infrastructure', location: 'Pune HQ / Hybrid', employmentType: 'Full-time', openPositions: 2, applicantsCount: 4, status: 'Published', publishDate: '2026-09-20', experienceLevel: 'Mid-Senior (3-6 yrs)', salaryRange: '₹16 - 25 LPA' },
  { id: 'JOB-203', title: 'Python & Frappe / ERPNext Specialist', department: 'IT & Engineering', location: 'Pune Global HQ', employmentType: 'Full-time', openPositions: 2, applicantsCount: 3, status: 'Published', publishDate: '2026-09-22', experienceLevel: 'Associate - Mid (2-4 yrs)', salaryRange: '₹12 - 18 LPA' },
  { id: 'JOB-204', title: 'Senior UI/UX & Design Systems Engineer', department: 'Product & Design', location: 'Pune Global HQ', employmentType: 'Full-time', openPositions: 1, applicantsCount: 3, status: 'Published', publishDate: '2026-09-25', experienceLevel: 'Senior (4-7 yrs)', salaryRange: '₹18 - 26 LPA' },
  { id: 'JOB-205', title: 'HR Talent Acquisition & People Operations Partner', department: 'Human Resources', location: 'Pune Global HQ', employmentType: 'Full-time', openPositions: 1, applicantsCount: 2, status: 'Published', publishDate: '2026-09-28', experienceLevel: 'Mid (3-5 yrs)', salaryRange: '₹10 - 15 LPA' },
];

export const INITIAL_JOB_APPLICANTS: JobApplicant[] = [
  // ==========================================
  // 1. APPLIED STAGE
  // ==========================================
  {
    id: 'APP-PPO-005',
    jobId: 'JOB-205',
    jobTitle: 'HR Talent Acquisition & People Operations Partner',
    applicantName: 'Preeti Bagal',
    email: 'preeti.bagal@ethxsoftcon.com',
    phone: '+91 98450 11205',
    candidateType: 'Intern PPO',
    internId: 'emp-020',
    stage: 'Applied',
    rating: 4.5,
    appliedDate: '2026-10-01',
    experienceYears: 0.3,
    currentCompany: 'ETHX Softcon (Internship Concluded 30 Sep 2026)',
    skills: ['HR Operations', 'Candidate Sourcing', 'Attendance Auditing', 'Onboarding'],
    expectedSalary: '₹5.2 LPA',
    noticePeriod: 'Immediate (Internship Finished)',
    location: 'Pune Global HQ',
    technicalScore: 88,
    internshipDetails: {
      completedPeriod: '01 Jul 2026 - 30 Sep 2026',
      mentorScore: 88,
      recommendation: 'Exceptional dedication in managing intern documentation, roster verification, and daily coordination during Q3.',
      mentorName: 'Niky Sharma (HR Admin)',
    },
    notes: 'Q3 Intern seeking permanent role in People Operations. Verified attendance audits and personnel record maintenance.',
  },
  {
    id: 'APP-101',
    jobId: 'JOB-201',
    jobTitle: 'Full-Stack Software Engineer (React / TypeScript / Node)',
    applicantName: 'Aditya Deshmukh',
    email: 'aditya.deshmukh@example.com',
    phone: '+91 98230 44120',
    candidateType: 'Lateral Hire',
    stage: 'Applied',
    rating: 4,
    appliedDate: '2026-10-02',
    experienceYears: 3,
    currentCompany: 'Cybage Software',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
    expectedSalary: '₹16 LPA',
    noticePeriod: '30 Days',
    location: 'Pune, India',
    notes: 'Strong candidate with full-stack React and Node experience; enthusiastic about high-scale SaaS products.',
  },
  {
    id: 'APP-102',
    jobId: 'JOB-202',
    jobTitle: 'Cloud DevOps & Site Reliability Engineer',
    applicantName: 'Pooja Kulkarni',
    email: 'pooja.kulkarni@example.com',
    phone: '+91 97654 32189',
    candidateType: 'Lateral Hire',
    stage: 'Applied',
    rating: 4,
    appliedDate: '2026-10-03',
    experienceYears: 3.5,
    currentCompany: 'Cognizant Cloud',
    skills: ['Docker', 'Kubernetes', 'AWS', 'Linux'],
    expectedSalary: '₹18 LPA',
    noticePeriod: '60 Days',
    location: 'Mumbai / Pune',
    notes: 'Experience managing containerized Kubernetes clusters on AWS; solid bash scripting.',
  },
  {
    id: 'APP-103',
    jobId: 'JOB-204',
    jobTitle: 'Senior UI/UX & Design Systems Engineer',
    applicantName: 'Kunal Sharma',
    email: 'kunal.sharma@example.com',
    phone: '+91 91234 56780',
    candidateType: 'Lateral Hire',
    stage: 'Applied',
    rating: 4,
    appliedDate: '2026-10-04',
    experienceYears: 3,
    currentCompany: 'Studio Pixel Design',
    skills: ['Figma', 'Tailwind CSS', 'Next.js', 'Design Systems'],
    expectedSalary: '₹15 LPA',
    noticePeriod: 'Immediate',
    location: 'Pune, India',
    notes: 'Submitted impressive portfolio showing custom dark-mode component libraries and interactive prototypes.',
  },

  // ==========================================
  // 2. SCREENING STAGE
  // ==========================================
  {
    id: 'APP-PPO-004',
    jobId: 'JOB-203',
    jobTitle: 'Python & Frappe / ERPNext Specialist',
    applicantName: 'Goraksh Kaduskar',
    email: 'goraksh.kaduskar@ethxsoftcon.com',
    phone: '+91 99220 33415',
    candidateType: 'Intern PPO',
    internId: 'emp-015',
    stage: 'Screening',
    rating: 4.5,
    appliedDate: '2026-10-01',
    experienceYears: 0.3,
    currentCompany: 'ETHX Softcon (Internship Concluded 30 Sep 2026)',
    skills: ['Python 3.12', 'Frappe Framework', 'MariaDB', 'DocType Modeling', 'ERPNext v15'],
    expectedSalary: '₹5.8 LPA',
    noticePeriod: 'Immediate (Internship Finished)',
    location: 'Pune Global HQ',
    technicalScore: 86,
    internshipDetails: {
      completedPeriod: '01 Jul 2026 - 30 Sep 2026',
      mentorScore: 86,
      recommendation: 'Completed backend tasks on Frappe MariaDB triggers and DocType validation. Ready for technical review round.',
      mentorName: 'Siva Kumar (IT Leadership)',
    },
    notes: 'Screened by Niky Sharma: Intern demonstrated sound fundamentals in Frappe ORM and server scripts. Recommended for technical panel.',
  },
  {
    id: 'APP-104',
    jobId: 'JOB-201',
    jobTitle: 'Full-Stack Software Engineer (React / TypeScript / Node)',
    applicantName: 'Sneha Patil',
    email: 'sneha.patil@example.com',
    phone: '+91 98901 23456',
    candidateType: 'Lateral Hire',
    stage: 'Screening',
    rating: 5,
    appliedDate: '2026-09-28',
    experienceYears: 4,
    currentCompany: 'Persistent Systems',
    skills: ['React 18', 'TypeScript', 'Express', 'Tailwind', 'Redis'],
    expectedSalary: '₹18 LPA',
    noticePeriod: '15 Days',
    location: 'Pune, India',
    technicalScore: 85,
    notes: 'Screened by Niky Sharma: excellent communication, demonstrated solid architectural grasp of state management.',
  },
  {
    id: 'APP-105',
    jobId: 'JOB-203',
    jobTitle: 'Python & Frappe / ERPNext Specialist',
    applicantName: 'Rohit Joshi',
    email: 'rohit.joshi@example.com',
    phone: '+91 99220 11234',
    candidateType: 'Lateral Hire',
    stage: 'Screening',
    rating: 4,
    appliedDate: '2026-09-29',
    experienceYears: 3,
    currentCompany: 'Tata Elxsi',
    skills: ['Python', 'Frappe Framework', 'MariaDB', 'REST APIs'],
    expectedSalary: '₹14 LPA',
    noticePeriod: '30 Days',
    location: 'Pune, India',
    notes: 'Screening round passed. Hands-on experience with Frappe DocTypes and custom hooks. Ready for technical round.',
  },
  {
    id: 'APP-106',
    jobId: 'JOB-205',
    jobTitle: 'HR Talent Acquisition & People Operations Partner',
    applicantName: 'Neha Verma',
    email: 'neha.verma@example.com',
    phone: '+91 98450 67890',
    candidateType: 'Lateral Hire',
    stage: 'Screening',
    rating: 5,
    appliedDate: '2026-09-30',
    experienceYears: 4.5,
    currentCompany: 'Wipro HR Operations',
    skills: ['Tech Sourcing', 'ATS Optimization', 'HR Compliance', 'Onboarding'],
    expectedSalary: '₹12 LPA',
    noticePeriod: '30 Days',
    location: 'Pune, India',
    notes: 'Experienced IT recruiter with direct background in engineering hiring pipelines and Frappe HRMS.',
  },

  // ==========================================
  // 3. TECHNICAL ROUND STAGE
  // ==========================================
  {
    id: 'APP-PPO-003',
    jobId: 'JOB-202',
    jobTitle: 'Cloud DevOps & Site Reliability Engineer',
    applicantName: 'Rushikesh Kulkarni',
    email: 'rushikesh.kulkarni@ethxsoftcon.com',
    phone: '+91 98760 99416',
    candidateType: 'Intern PPO',
    internId: 'emp-016',
    stage: 'Technical Round',
    rating: 5,
    appliedDate: '2026-09-29',
    experienceYears: 0.3,
    currentCompany: 'ETHX Softcon (Internship Concluded 30 Sep 2026)',
    skills: ['Docker', 'Linux Admin', 'GitHub Actions', 'Prometheus', 'Nginx Reverse Proxy'],
    expectedSalary: '₹6.2 LPA',
    noticePeriod: 'Immediate (Internship Finished)',
    location: 'Pune Global HQ',
    technicalScore: 90,
    internshipDetails: {
      completedPeriod: '01 Jul 2026 - 30 Sep 2026',
      mentorScore: 90,
      recommendation: 'Managed internal staging deployments and container health monitoring during Q3. Strong Linux command-line skills.',
      mentorName: 'Siva Kumar (IT Director)',
    },
    notes: 'Technical Interview round with Siva Kumar: 90/100. Successfully solved automated deployment rollback scenario.',
    interviewNotes: [
      {
        stage: 'Internship Capstone Review',
        interviewer: 'Siva Kumar (IT Leadership)',
        score: 90,
        notes: 'Demonstrated solid grasp of Docker compose configurations, systemd services, and health probes.',
        date: '2026-10-02',
      },
    ],
  },
  {
    id: 'APP-107',
    jobId: 'JOB-202',
    jobTitle: 'Cloud DevOps & Site Reliability Engineer',
    applicantName: 'Varun Nair',
    email: 'varun.nair@example.com',
    phone: '+91 98765 43210',
    candidateType: 'Lateral Hire',
    stage: 'Technical Round',
    rating: 5,
    appliedDate: '2026-09-22',
    experienceYears: 5,
    currentCompany: 'Infosys Cloud Core',
    skills: ['Terraform', 'Kubernetes', 'CI/CD Pipelines', 'Docker', 'Prometheus'],
    expectedSalary: '₹22 LPA',
    noticePeriod: '30 Days',
    location: 'Bengaluru / Pune',
    technicalScore: 94,
    notes: 'Technical Interview with Siva Kumar: 94/100. Flawless live Kubernetes deployment, deep understanding of Nginx and zero-downtime deployments.',
    interviewNotes: [
      {
        stage: 'Technical Round 1',
        interviewer: 'Siva Kumar (IT Leadership)',
        score: 94,
        notes: 'Exceptional troubleshooting ability under live container failure scenario. Highly recommended for final round.',
        date: '2026-10-02',
      },
    ],
  },
  {
    id: 'APP-108',
    jobId: 'JOB-201',
    jobTitle: 'Full-Stack Software Engineer (React / TypeScript / Node)',
    applicantName: 'Ananya Sen',
    email: 'ananya.sen@example.com',
    phone: '+91 98300 12345',
    candidateType: 'Lateral Hire',
    stage: 'Technical Round',
    rating: 5,
    appliedDate: '2026-09-24',
    experienceYears: 4,
    currentCompany: 'Mindtree Ltd',
    skills: ['React 18', 'TypeScript', 'GraphQL', 'Node.js', 'Jest'],
    expectedSalary: '₹19 LPA',
    noticePeriod: '15 Days',
    location: 'Pune, India',
    technicalScore: 91,
    notes: 'Technical assessment passed with 91/100. Clean component modularity and comprehensive test coverage.',
  },
  {
    id: 'APP-109',
    jobId: 'JOB-203',
    jobTitle: 'Python & Frappe / ERPNext Specialist',
    applicantName: 'Harsh Vardhan',
    email: 'harsh.vardhan@example.com',
    phone: '+91 99110 55432',
    candidateType: 'Lateral Hire',
    stage: 'Technical Round',
    rating: 5,
    appliedDate: '2026-09-25',
    experienceYears: 4,
    currentCompany: 'ERP Solutions Ltd',
    skills: ['ERPNext v15', 'DocType Modeling', 'Server Scripts', 'Python 3.12'],
    expectedSalary: '₹16 LPA',
    noticePeriod: '30 Days',
    location: 'Pune, India',
    technicalScore: 89,
    notes: 'Technical round completed: accurately solved multi-tenant bench isolation and custom server script triggers.',
  },

  // ==========================================
  // 4. HR INTERVIEW STAGE
  // ==========================================
  {
    id: 'APP-PPO-002',
    jobId: 'JOB-204',
    jobTitle: 'Senior UI/UX & Design Systems Engineer',
    applicantName: 'Deepti Tiwari',
    email: 'deepti.tiwari@ethxsoftcon.com',
    phone: '+91 98220 11414',
    candidateType: 'Intern PPO',
    internId: 'emp-014',
    stage: 'HR Interview',
    rating: 5,
    appliedDate: '2026-09-28',
    experienceYears: 0.3,
    currentCompany: 'ETHX Softcon (Internship Concluded 30 Sep 2026)',
    skills: ['Figma Design Tokens', 'React 18', 'Tailwind CSS', 'Accessible UI', 'Micro-interactions'],
    expectedSalary: '₹6.0 LPA',
    noticePeriod: 'Immediate (Internship Finished)',
    location: 'Pune Global HQ',
    technicalScore: 94,
    internshipDetails: {
      completedPeriod: '01 Jul 2026 - 30 Sep 2026',
      mentorScore: 94,
      recommendation: 'Consistently crafted clean, accessible UI components. Designed dark-mode design tokens and navigation drawer.',
      mentorName: 'Niky Sharma (HR) & Senior UI Lead',
    },
    notes: 'Internship completed on 30 Sep 2026. Technical evaluation cleared with 94/100. HR interview scheduled with Niky Sharma for official full-time compensation alignment.',
    interviewNotes: [
      {
        stage: 'Technical Review',
        interviewer: 'Design & Engineering Panel',
        score: 94,
        notes: 'Strong visual hierarchy, flawless component prototyping and high-velocity delivery.',
        date: '2026-09-28',
      },
      {
        stage: 'HR & PPO Discussion',
        interviewer: 'Niky Sharma (HR Admin)',
        score: 95,
        notes: 'High cultural alignment and team spirit. Formulating official PPO package for ₹6.0 LPA.',
        date: '2026-10-03',
      },
    ],
  },
  {
    id: 'APP-110',
    jobId: 'JOB-204',
    jobTitle: 'Senior UI/UX & Design Systems Engineer',
    applicantName: 'Tanvi Shinde',
    email: 'tanvi.shinde@example.com',
    phone: '+91 98220 98765',
    candidateType: 'Lateral Hire',
    stage: 'HR Interview',
    rating: 5,
    appliedDate: '2026-09-18',
    experienceYears: 5.5,
    currentCompany: 'Zeta Global',
    skills: ['Design Tokens', 'Tailwind CSS', 'Figma', 'WCAG A11y', 'React'],
    expectedSalary: '₹24 LPA',
    noticePeriod: '15 Days',
    location: 'Pune Global HQ',
    technicalScore: 96,
    notes: 'Passed Technical Round with 96/100. HR culture alignment and compensation discussion in progress with Niky Sharma.',
    interviewNotes: [
      {
        stage: 'Technical Evaluation',
        interviewer: 'Design & Frontend Committee',
        score: 96,
        notes: 'Top tier UI engineer with deep knowledge of accessible micro-interactions and dark-mode tokens.',
        date: '2026-09-28',
      },
      {
        stage: 'HR Leadership Round',
        interviewer: 'Niky Sharma (Main HR)',
        score: 95,
        notes: 'Great leadership presence, aligns with ETHX product vision. Preparing offer proposal.',
        date: '2026-10-04',
      },
    ],
  },
  {
    id: 'APP-111',
    jobId: 'JOB-201',
    jobTitle: 'Full-Stack Software Engineer (React / TypeScript / Node)',
    applicantName: 'Abhishek Roy',
    email: 'abhishek.roy@example.com',
    phone: '+91 98111 22334',
    candidateType: 'Lateral Hire',
    stage: 'HR Interview',
    rating: 5,
    appliedDate: '2026-09-19',
    experienceYears: 5,
    currentCompany: 'Tech Mahindra',
    skills: ['Next.js', 'Distributed Systems', 'Tailwind', 'Microservices'],
    expectedSalary: '₹20 LPA',
    noticePeriod: '30 Days',
    location: 'Pune, India',
    technicalScore: 88,
    notes: 'Technical rounds cleared. Finalizing CTC alignment and onboarding date with HR.',
  },

  // ==========================================
  // 5. OFFER SENT STAGE (READY FOR PERMANENT PROMOTION)
  // ==========================================
  {
    id: 'APP-PPO-001',
    jobId: 'JOB-201',
    jobTitle: 'Full-Stack Software Engineer (React / TypeScript / Node)',
    applicantName: 'Krishna Tiwari',
    email: 'krishna.tiwari@ethxsoftcon.com',
    phone: '+91 98100 22421',
    candidateType: 'Intern PPO',
    internId: 'emp-021',
    stage: 'Offer Sent',
    rating: 5,
    appliedDate: '2026-09-28',
    experienceYears: 0.3,
    currentCompany: 'ETHX Softcon (Internship Concluded 30 Sep 2026)',
    skills: ['React 18', 'TypeScript', 'Node.js Express', 'Frappe / ERPNext', 'Tailwind CSS', 'Jest / Vitest'],
    expectedSalary: '₹6.5 LPA',
    noticePeriod: 'Immediate (Internship Finished)',
    location: 'Pune Global HQ',
    technicalScore: 98,
    internshipDetails: {
      completedPeriod: '01 Jul 2026 - 30 Sep 2026',
      mentorScore: 98,
      recommendation: 'Top performer of the Q3 cohort. Demonstrated enterprise software craftsmanship across HRMS modules, Frappe client integration, and 100% test coverage. Highest recommendation for immediate promotion to permanent Full-Time Employee (Associate Software Engineer - L1).',
      mentorName: 'Siva Kumar (IT Director) & Niky Sharma (HR Admin)',
    },
    offerDetails: {
      salary: '₹6,50,000 / year (Fixed Salaried)',
      designation: 'Associate Software Engineer - L1',
      joiningDate: '2026-10-01',
      status: 'Accepted',
    },
    notes: 'Official Pre-Placement Offer (PPO) dispatched. Candidate has accepted offer! Ready for 1-Click Permanent Employee Promotion & Payroll Activation.',
    interviewNotes: [
      {
        stage: 'Internship Capstone & Code Audit',
        interviewer: 'Siva Kumar (IT Director)',
        score: 98,
        notes: 'Outstanding architectural mastery. Wrote strict TypeScript domain logic, responsive navigation drawer, and Frappe client mocks.',
        date: '2026-09-28',
      },
      {
        stage: 'PPO Executive Approval & Compensation',
        interviewer: 'Niky Sharma (HR Admin) & Ram Chaturvedi (Director)',
        score: 98,
        notes: 'Director approval signed. Pre-Placement Offer issued for ₹6.5 LPA effective 1 October 2026.',
        date: '2026-09-30',
      },
    ],
  },
  {
    id: 'APP-112',
    jobId: 'JOB-202',
    jobTitle: 'Cloud DevOps & Site Reliability Engineer',
    applicantName: 'Meera Iyer',
    email: 'meera.iyer@example.com',
    phone: '+91 97110 99887',
    candidateType: 'Lateral Hire',
    stage: 'Offer Sent',
    rating: 5,
    appliedDate: '2026-09-10',
    experienceYears: 6,
    currentCompany: 'Barclays Global Tech',
    skills: ['CKA Certified', 'Kubernetes', 'GitHub Actions', 'AWS DevOps'],
    expectedSalary: '₹24 LPA',
    noticePeriod: 'Serving Notice',
    location: 'Pune Global HQ',
    technicalScore: 98,
    notes: 'Offer letter dispatched on 1 Oct 2026. Official joining date confirmed for 1 November 2026.',
    offerDetails: {
      salary: '₹23.5 LPA (Fixed + Performance Incentive)',
      designation: 'Senior Cloud & DevOps Engineer',
      joiningDate: '2026-11-01',
      status: 'Sent',
    },
    interviewNotes: [
      {
        stage: 'Architecture Panel',
        interviewer: 'Ram Chaturvedi & Siva Kumar',
        score: 98,
        notes: 'Outstanding technical and strategic competence. Unanimous offer recommendation.',
        date: '2026-09-29',
      },
    ],
  },
  {
    id: 'APP-113',
    jobId: 'JOB-203',
    jobTitle: 'Python & Frappe / ERPNext Specialist',
    applicantName: 'Vikram Solanki',
    email: 'vikram.solanki@example.com',
    phone: '+91 98200 44556',
    candidateType: 'Lateral Hire',
    stage: 'Offer Sent',
    rating: 5,
    appliedDate: '2026-09-12',
    experienceYears: 4.5,
    currentCompany: 'Amdocs Software',
    skills: ['Frappe Bench', 'Python', 'PostgreSQL', 'High-Availability ERP'],
    expectedSalary: '₹18 LPA',
    noticePeriod: 'Serving Notice',
    location: 'Pune Global HQ',
    technicalScore: 93,
    notes: 'Offer accepted! Verification and background check initiated. Joining on 24 October 2026.',
    offerDetails: {
      salary: '₹17.5 LPA',
      designation: 'Backend Systems Engineer (ERPNext)',
      joiningDate: '2026-10-24',
      status: 'Accepted',
    },
  },
];

export const INITIAL_GOALS: PerformanceGoal[] = [
  { id: 'G-101', employeeId: 'ETHX-021', title: 'Complete Q3 Internship Capstone Deliverable', description: 'Deliver full-fidelity module specifications and evaluation evidence before 30 Sep 2026.', category: 'Operational', progress: 90, dueDate: '2026-09-30', weightage: 50, status: 'In Progress' },
];

export const INITIAL_SKILLS: SkillMatrixItem[] = [
  {
    id: 'SK-01',
    skillName: 'React 18, TypeScript & Next.js UI/UX',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 12,
    targetDemand: 14,
    gapPriority: 'Moderate',
    learningTrack: 'Frontend Engineering Specialization',
    description: 'Concurrent rendering, memoization, atomic design systems, and TypeScript 5.7 strict typing.',
    certifiedEmployees: ['Shubham Patane', 'Saurav Sarkar', 'Shruti Pawar', 'Krishna Tiwari', 'Rushikesh Kulkarni'],
  },
  {
    id: 'SK-02',
    skillName: 'Python, Frappe Framework & ERPNext',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Advanced',
    employeeCount: 8,
    targetDemand: 10,
    gapPriority: 'Moderate',
    learningTrack: 'Frappe Cloud Architecture',
    description: 'DocType modeling, server scripts, RESTful API hooks, and Frappe bench administration on port 8280.',
    certifiedEmployees: ['Siva Kumar', 'Shubham Patane', 'Deepti Tiwari', 'Goraksh Kaduskar'],
  },
  {
    id: 'SK-03',
    skillName: 'Docker, Linux Server & Nginx Reverse Proxy',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Intermediate',
    employeeCount: 7,
    targetDemand: 8,
    gapPriority: 'Moderate',
    learningTrack: 'Cloud DevOps & Containerization',
    description: 'Multi-stage Docker builds, Alpine Linux, Nginx SPA routing fallback, and container networking.',
    certifiedEmployees: ['Siva Kumar', 'Virender Kumar', 'Krishna Tiwari', 'Utkarsh'],
  },
  {
    id: 'SK-04',
    skillName: 'MariaDB / MySQL Relational Schema & ACID',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 9,
    targetDemand: 10,
    gapPriority: 'Optimal',
    learningTrack: 'Database Engineering',
    description: 'Relational data modeling, indexing, foreign keys, transaction isolation, and query optimization.',
    certifiedEmployees: ['Siva Kumar', 'Saurav Sarkar', 'Vishal Walunj', 'Preeti Bagal'],
  },
  {
    id: 'SK-05',
    skillName: 'RESTful API Contracts & Client Data Sync',
    category: 'Engineering',
    proficiencyLevel: 'Expert',
    employeeCount: 11,
    targetDemand: 12,
    gapPriority: 'Optimal',
    learningTrack: 'Distributed API Systems',
    description: 'JSON schemas, bearer token authentication, idempotent state sync, and optimistic UI updates.',
    certifiedEmployees: ['Siva Kumar', 'Shruti Pawar', 'Ganesh Kulkarni', 'Sayali Mahant'],
  },
  {
    id: 'SK-06',
    skillName: 'Vitest, Unit Testing & QA Automation',
    category: 'Engineering',
    proficiencyLevel: 'Intermediate',
    employeeCount: 6,
    targetDemand: 8,
    gapPriority: 'Moderate',
    learningTrack: 'Software Quality Assurance',
    description: 'Component unit tests, API integration tests, assertion coverage, and regression prevention.',
    certifiedEmployees: ['Shubham Patane', 'Shruti Pawar', 'Shakti Thakur'],
  },
  {
    id: 'SK-07',
    skillName: 'Statutory Payroll, PF & Indian Labor Compliance',
    category: 'HR & Operations',
    proficiencyLevel: 'Expert',
    employeeCount: 2,
    targetDemand: 2,
    gapPriority: 'Optimal',
    learningTrack: 'HR Legal & Statutory Governance',
    description: 'Salary slip generation, tax deductions, PF calculation, and labor compliance regulation.',
    certifiedEmployees: ['Niky Sharma', 'Madhavi Singh'],
  },
  {
    id: 'SK-08',
    skillName: 'Performance Evaluation Rubrics & OKRs',
    category: 'HR & Operations',
    proficiencyLevel: 'Advanced',
    employeeCount: 3,
    targetDemand: 3,
    gapPriority: 'Optimal',
    learningTrack: 'Strategic HR Performance',
    description: '7-Factor evaluation rubrics, conversion recommendation pipelines, and OKR milestone tracking.',
    certifiedEmployees: ['Niky Sharma', 'Madhavi Singh', 'Ram Chaturvedi'],
  },
  {
    id: 'SK-09',
    skillName: 'Redis In-Memory Caching & Task Queues',
    category: 'Cloud & Infrastructure',
    proficiencyLevel: 'Intermediate',
    employeeCount: 5,
    targetDemand: 6,
    gapPriority: 'Moderate',
    learningTrack: 'High-Performance Caching',
    description: 'Redis 6.2 key-value caching, session token storage, and asynchronous background worker queues.',
    certifiedEmployees: ['Siva Kumar', 'Krishna Tiwari', 'Goraksh Kaduskar'],
  },
  {
    id: 'SK-10',
    skillName: 'Git Version Control & CI/CD Pipelines',
    category: 'Engineering',
    proficiencyLevel: 'Advanced',
    employeeCount: 18,
    targetDemand: 18,
    gapPriority: 'Optimal',
    learningTrack: 'DevOps & Collaboration',
    description: 'Git branching, semantic commit tagging, pull request reviews, and GitHub Actions automation.',
    certifiedEmployees: ['All 14 Engineers & Interns', 'Siva Kumar', 'Archit Sharma'],
  },
];

export const INITIAL_ASSETS: AssetRecord[] = [
  // 1. Unpaid Intern Cohort (8 Asus Vivobooks)
  {
    id: 'AST-ASUS-014',
    assetCode: 'ETHX-VIVO-014',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-014',
    assignedEmployeeName: 'Deepti Tiwari',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77014',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-015',
    assetCode: 'ETHX-VIVO-015',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-015',
    assignedEmployeeName: 'Goraksh Kaduskar',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77015',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-016',
    assetCode: 'ETHX-VIVO-016',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-016',
    assignedEmployeeName: 'Rushikesh Kulkarni',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77016',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-017',
    assetCode: 'ETHX-VIVO-017',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-017',
    assignedEmployeeName: 'Utkarsh',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77017',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-018',
    assetCode: 'ETHX-VIVO-018',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-018',
    assignedEmployeeName: 'Shakti Thakur',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77018',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-019',
    assetCode: 'ETHX-VIVO-019',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-019',
    assignedEmployeeName: 'Sayali Mahant',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77019',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-020',
    assetCode: 'ETHX-VIVO-020',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • 15.6" FHD OLED',
    assignedTo: 'ETHX-020',
    assignedEmployeeName: 'Preeti Bagal',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77020',
    condition: 'Excellent',
  },
  {
    id: 'AST-ASUS-021',
    assetCode: 'ETHX-VIVO-021',
    assetName: 'Asus Vivobook 15 Pro OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook Pro 15 OLED M6500',
    specifications: 'AMD Ryzen 7 / Intel Core i5 • 16GB DDR5 • 512GB NVMe SSD • NVIDIA RTX Graphics',
    assignedTo: 'ETHX-021',
    assignedEmployeeName: 'Krishna Tiwari',
    assignedDepartment: 'IT & Engineering (Cloud Lab)',
    allocatedDate: '2026-07-01',
    status: 'In Use',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VBP-77021',
    condition: 'Brand New',
  },

  // 2. Full-time Employees & HR (HP Laptops)
  {
    id: 'AST-HP-004',
    assetCode: 'ETHX-HP-004',
    assetName: 'HP ZBook Firefly 14 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ZBook Firefly 14 G10 Mobile Workstation',
    specifications: 'Intel Core i7 13th Gen • 32GB DDR5 • 1TB NVMe Gen4 SSD • NVIDIA RTX A500',
    assignedTo: 'ETHX-004',
    assignedEmployeeName: 'Siva Kumar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-05-15',
    status: 'In Use',
    purchaseDate: '2023-05-01',
    warrantyExpiry: '2026-05-01',
    serialNumber: '5CG3190HP4',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-005',
    assetCode: 'ETHX-HP-005',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR5 • 512GB NVMe SSD • Sure View Privacy',
    assignedTo: 'ETHX-005',
    assignedEmployeeName: 'Niky Sharma',
    assignedDepartment: 'Human Resources',
    allocatedDate: '2023-06-01',
    status: 'In Use',
    purchaseDate: '2023-05-20',
    warrantyExpiry: '2026-05-20',
    serialNumber: '5CG3210HP5',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-006',
    assetCode: 'ETHX-HP-006',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR5 • 512GB NVMe SSD • HP Wolf Security',
    assignedTo: 'ETHX-006',
    assignedEmployeeName: 'Madhavi Singh',
    assignedDepartment: 'Human Resources',
    allocatedDate: '2023-11-10',
    status: 'In Use',
    purchaseDate: '2023-11-01',
    warrantyExpiry: '2026-11-01',
    serialNumber: '5CG3450HP6',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-007',
    assetCode: 'ETHX-HP-007',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-007',
    assignedEmployeeName: 'Shubham Patane',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-11-20',
    status: 'In Use',
    purchaseDate: '2023-11-15',
    warrantyExpiry: '2026-11-15',
    serialNumber: '5CG3520HP7',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-008',
    assetCode: 'ETHX-HP-008',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-008',
    assignedEmployeeName: 'Saurav Sarkar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-12-05',
    status: 'In Use',
    purchaseDate: '2023-11-28',
    warrantyExpiry: '2026-11-28',
    serialNumber: '5CG3590HP8',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-009',
    assetCode: 'ETHX-HP-009',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-009',
    assignedEmployeeName: 'Vishal Walunj',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2024-02-01',
    status: 'In Use',
    purchaseDate: '2024-01-20',
    warrantyExpiry: '2027-01-20',
    serialNumber: '5CG4080HP9',
    condition: 'Good',
  },
  {
    id: 'AST-HP-010',
    assetCode: 'ETHX-HP-010',
    assetName: 'HP EliteBook 840 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G10 Enterprise',
    specifications: 'Intel Core i7 13th Gen • 16GB DDR5 • 512GB NVMe SSD • HP Wolf Security',
    assignedTo: 'ETHX-010',
    assignedEmployeeName: 'Shruti Pawar',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2023-08-15',
    status: 'In Use',
    purchaseDate: '2023-08-01',
    warrantyExpiry: '2026-08-01',
    serialNumber: '5CG3380HP10',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-011',
    assetCode: 'ETHX-HP-011',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • 15.6" Anti-glare',
    assignedTo: 'ETHX-011',
    assignedEmployeeName: 'Ganesh Kulkarni',
    assignedDepartment: 'IT & Engineering',
    allocatedDate: '2024-01-10',
    status: 'In Use',
    purchaseDate: '2023-12-20',
    warrantyExpiry: '2026-12-20',
    serialNumber: '5CG4010HP11',
    condition: 'Good',
  },
  {
    id: 'AST-HP-012',
    assetCode: 'ETHX-HP-012',
    assetName: 'HP EliteBook 650 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 650 G9 Secure Remote',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • VPN Hardware Token Enrolled',
    assignedTo: 'ETHX-012',
    assignedEmployeeName: 'Archit Sharma',
    assignedDepartment: 'Contract Operations (Pan-India)',
    allocatedDate: '2023-11-15',
    status: 'In Use',
    purchaseDate: '2023-11-01',
    warrantyExpiry: '2026-11-01',
    serialNumber: '5CG3480HP12',
    condition: 'Good',
  },
  {
    id: 'AST-HP-013',
    assetCode: 'ETHX-HP-013',
    assetName: 'HP EliteBook 650 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 650 G9 Secure Remote',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • VPN Hardware Token Enrolled',
    assignedTo: 'ETHX-013',
    assignedEmployeeName: 'Rajnesh',
    assignedDepartment: 'Contract Operations (Pan-India)',
    allocatedDate: '2024-02-12',
    status: 'In Use',
    purchaseDate: '2024-02-01',
    warrantyExpiry: '2027-02-01',
    serialNumber: '5CG4120HP13',
    condition: 'Good',
  },

  // 3. Executive Board Directors (HP Enterprise & Spectre)
  {
    id: 'AST-HP-001',
    assetCode: 'ETHX-HP-001',
    assetName: 'HP Spectre x360 16"',
    category: 'Laptop',
    brand: 'HP',
    model: 'Spectre x360 2-in-1 OLED',
    specifications: 'Intel Core i7 13th Gen • 32GB LPDDR5 • 1TB NVMe Gen4 SSD • 4K OLED Touch',
    assignedTo: 'ETHX-001',
    assignedEmployeeName: 'Ram Chaturvedi',
    assignedDepartment: 'Executive Board',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2420HP1',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-002',
    assetCode: 'ETHX-HP-002',
    assetName: 'HP Elite Dragonfly G4',
    category: 'Laptop',
    brand: 'HP',
    model: 'Elite Dragonfly G4 Ultralight',
    specifications: 'Intel Core i7 13th Gen • 32GB LPDDR5 • 1TB SSD • 5G LTE eSIM Active',
    assignedTo: 'ETHX-002',
    assignedEmployeeName: 'Rohan',
    assignedDepartment: 'Executive Board',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2440HP2',
    condition: 'Excellent',
  },
  {
    id: 'AST-HP-003',
    assetCode: 'ETHX-HP-003',
    assetName: 'HP ZBook Studio G9 Workstation',
    category: 'Laptop',
    brand: 'HP',
    model: 'ZBook Studio G9 Workstation',
    specifications: 'Intel Core i9 12th Gen • 32GB DDR5 • 1TB SSD • NVIDIA RTX 3070 Ti',
    assignedTo: 'ETHX-003',
    assignedEmployeeName: 'Virender Kumar',
    assignedDepartment: 'Executive Board (US Operations)',
    allocatedDate: '2022-11-01',
    status: 'In Use',
    purchaseDate: '2022-10-15',
    warrantyExpiry: '2025-10-15',
    serialNumber: '5CG2490HP3',
    condition: 'Excellent',
  },

  // 4. IT Inventory Reserves (Available Spares & Service)
  {
    id: 'AST-ASUS-RES-01',
    assetCode: 'ETHX-VIVO-RES1',
    assetName: 'Asus Vivobook 15 OLED',
    category: 'Laptop',
    brand: 'ASUS',
    model: 'Vivobook 15 OLED K513',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB NVMe SSD • Unboxed / Provisioned',
    status: 'Available',
    purchaseDate: '2026-06-25',
    warrantyExpiry: '2028-06-25',
    serialNumber: 'ASUS-VB-77091',
    condition: 'Brand New',
  },
  {
    id: 'AST-HP-RES-01',
    assetCode: 'ETHX-HP-RES1',
    assetName: 'HP ProBook 450 G10',
    category: 'Laptop',
    brand: 'HP',
    model: 'ProBook 450 G10 Business Laptop',
    specifications: 'Intel Core i5 13th Gen • 16GB DDR4 • 512GB SSD • IT Pune Spare',
    status: 'Available',
    purchaseDate: '2024-03-01',
    warrantyExpiry: '2027-03-01',
    serialNumber: '5CG4110HP-RES',
    condition: 'Brand New',
  },
  {
    id: 'AST-HP-MNT-01',
    assetCode: 'ETHX-HP-MNT1',
    assetName: 'HP EliteBook 840 G9',
    category: 'Laptop',
    brand: 'HP',
    model: 'EliteBook 840 G9 Enterprise',
    specifications: 'Intel Core i5 12th Gen • 16GB DDR4 • 512GB SSD • Battery Diagnostic',
    status: 'Under Maintenance',
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    serialNumber: '5CG3010HP-MNT',
    condition: 'Needs Service',
  },
];

export const INITIAL_NOTIFICATIONS: HRNotification[] = [
  { id: 'NOTIF-01', title: 'Internship Evaluation Review Period Open', message: 'Evaluation period active for 8 unpaid interns concluding on 30 Sep 2026.', timestamp: '1 hour ago', type: 'performance', read: false, actionUrl: '/internships' },
];
